site_name: Kimchi
repo_name: kimchi
repo_url: https://github.com/r0adkll/kimchi
site_description: "Cross-module component and dependency merging library for kotlin-inject"
site_author: r0adkll
remote_branch: gh-pages

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: assets/logo.svg
  palette:
      # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: kimchi
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

      # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Suse
    code: Jetbrains Mono

  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate

markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - tables
  - admonition
  - attr_list
  - md_in_html

nav:
  - 'Introduction': index.md
  - 'Tutorial': tutorial.md
  - 'Installation': setup.md
  - 'Components': components.md
  - 'Bindings': bindings.md
  - 'Modules': modules.md
  - 'Circuit': circuit.md
